# yaml 配置  failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create
#LLB definition: unexpected status code [manifests stretch-slim]: 403 For 这类错误，直接 docker pull debain:strech-slim
version: "3.7"
services:
  mysql:
    image: "mysql:8.0.19"
    ports:
      - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "bluebell"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./init.sql:/data/application/init.sql
  redis507:
    image: "redis:5.0.7"
    ports:
      - "26379:6379"
  bubble_app:
    build: .
    command: sh -c "./wait-for.sh mysql:3306 redis507:6379 -- ./bluebell_app ./conf/config.yaml"
    depends_on:
      - mysql
      - redis507
    ports:
      - "8888:8080"